<h1 style="color:#D30982;">Vectors as Numpy Arrays</h1>

Python's list data type is useful for many things. We can use lists to store collections of information, get elements, etc. Vectors are also a collection of numbers stored in a particular order. But **many of the functions we want to perform on vectors (i.e. the dot product, vector addition, vector multiplication, etc.) are not available natively through python lists.** However, we can use a python package that is ubiquitously used by python users: `numpy`. With `numpy`, we can do all sorts of vector calculates (and much more besides). We will only introduce you to a small fraction of the functionality provided by `numpy`, much of which requires mathematical understanding beyond the scope of this course.

<h2 style="color:#9A11DA;">Importing Numpy</h2>

To start, we need to `import numpy`, a statement which tells python to load all the functionality we might want to use from this package. We'll learn more about using external packages in a separate module, but for now, you can use the following import statement.

In [2]:
import numpy as np

We've now imported numpy and we can use the functions it provides. The second part of the statement (`as np`) provides a nickname to `numpy`. Because `numpy` is used so frequently, `np` has become the standard way to shorten the code used to refer to its functionality. We'll use that standard in all our code. Whenever you see a statement saying `"name 'np' is not defined"`, this means you have not run `import numpy as np` yet, and you should do so before trying that piece of code again.

<h2 style="color:#9A11DA;">Creating Numpy Arrays</h2>

To initialize a numpy array, we'll call the following statement:

In [4]:
my_numpy_array = np.array([4,3,-2])
print(my_numpy_array)

[ 4  3 -2]


You can see that this array looks very similar to a list when printed, but actually, has a whole bunch of functionality that is different from lists. To see how let's make a pair of lists (and their corresponding numppy arrays.

In [5]:
list_1 = [1,3,-2]
list_2 = [5,1,4]
np_array_1 = np.array(list_1)
np_array_2 = np.array(list_2)

Now let's try a simple opteration: addition.

In [6]:
print(list_1 + list_2)
print(np_array_1 + np_array_2)

[1, 3, -2, 5, 1, 4]
[6 4 2]


You'll notice that python interprets addition of lists as *concatenating* them together, creating. a longer list. Numpy arrays work differently. Numpy adds each element of the corresponding arrays together, just like we would vectors!

<h2 style="color:#9A11DA;">Vector Operations with Numpy</h2>

Manipulating vectors and matrices is where the `numpy` module truly shines. You can spend some time familiarizing with vectors and their operations by playing with the following code snippets.

**Row Vector.** A row vector is created using the function `array` in `numpy`. The entries of the vector are separated by a comma and are enclosed in a square bracket. The following line defines a three dimensional vector.

In [7]:
import numpy as np
vector = np.array([9, 8, 6])
print(vector)

[9 8 6]


**Getting Vector Elements.** Once we have defined a vector, it is easy to extract a single element by specifying its index. Indices are ordered in ascending order starting from $0$. Let's get the second element of both `row_vec` and `col_vec`.

In [11]:
print("The second entry of 'vector' is'", vector[1])

The second entry of 'vector' is' 8


**Adding Vectors.** You can add vectors with +, as long as they're either both row vectors or both column vectors and have the same dimension:

In [12]:
vector_1=np.array([9,8,6])
vector_2=np.array([1,2,3])
print(vector_1+vector_2)

[10 10  9]


**Multiplication by a Scalar.** We can also multiply a row or column vector by a scalar as follows.

In [13]:
vector_scaled=5*vector
print('Scaled row vector', vector_scaled)

Scaled row vector [45 40 30]


**Inner Product.** The inner product, or dot product, uses `np.dot()`. Recall that this is a scalar quantity. Notice that the format of the output is slightly differend depending on whether we use vectors of the same type. Don't be too worried about this, you can simply adjust your output to be in whatever format you need it.

In [15]:
dot_product = np.dot(vector_1, vector_2)
print(dot_product)

43


We can also use the following syntax:

In [14]:
dot_product2 = vector_1.dot(vector_2)
print(dot_product2)

43


**Magnitude.** The magnitude, or norm of the vector, is a function in the `linalg` sub-package in `numpy`. To access functions in sub-packages in python, we use `package.subpackage.function`. In this case we use `np.linalg.norm()` as follows:

In [ ]:
magnitude=np.linalg.norm(col_vec)
print(magnitude)

Notice that transforming a vector from a column to a row and vice versa doesn't affect its length:

In [ ]:
magnitude=np.linalg.norm(vector)
print(magnitude)

<h1 style="color:#D30982;">Exercises</h1>

1. First, import `numpy`. Then create the following variables:
    - a variable `a_4` that stores a four-dimensional numpy row vector with real entries of your choice
    - a variable `b_4` that stores a four-dimensional numpy row vector with real entries of your choice
    - a variable  `a_2` that stores a two-dimensional numpy row vector with real entries of your choice
    - a variable `b_2` that stores a two-dimensional numpy row vector with real entries of your choice

2. Use the `norm` function to determine the magnitude of the vector `a_4 + b_4`.

3. Calculate the inner product of:
    - `a_4` and `b_4`
    - `a_2` and `b_2`

4. Create two complex row vectors in python, of the same dimension. 
    - calculate the inner product of these two vectors and assign its value to an output variable `v`
    - calculate the real part of the first element of `v`

5. Create two real vectors of the same dimension. Create a new vector that is a linear combination of the first two.